name    'sbadia-allknowingdns'
version '0.0.1'
source  'https://github.com/sbadia/puppet-allknowingdns'
author  'Sebastien Badia'
license 'GPLv3'
summary 'Puppet AllKnowingDNS Module'
description 'Module to install AllKnowingDNS using puppet'
project_page 'https://github.com/sbadia/puppet-allknowingdns/'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
